# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 581)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoBox = QtWidgets.QGroupBox(self.centralwidget)
        self.videoBox.setTitle("")
        self.videoBox.setObjectName("videoBox")
        self.gridLayout = QtWidgets.QGridLayout(self.videoBox)
        self.gridLayout.setObjectName("gridLayout")
        self.videoFrame = QtWidgets.QLabel(self.videoBox)
        self.videoFrame.setMinimumSize(QtCore.QSize(300, 450))
        self.videoFrame.setText("")
        self.videoFrame.setScaledContents(True)
        self.videoFrame.setObjectName("videoFrame")
        self.gridLayout.addWidget(self.videoFrame, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.videoBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.LoadDatabaseButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadDatabaseButton.sizePolicy().hasHeightForWidth())
        self.LoadDatabaseButton.setSizePolicy(sizePolicy)
        self.LoadDatabaseButton.setObjectName("LoadDatabaseButton")
        self.horizontalLayout.addWidget(self.LoadDatabaseButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 865, 21))
        self.menubar.setObjectName("menubar")
        self.actionLoadDatabase = QtWidgets.QMenu(self.menubar)
        self.actionLoadDatabase.setObjectName("actionLoadDatabase")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_faces = QtWidgets.QAction(MainWindow)
        self.actionLoad_faces.setObjectName("actionLoad_faces")
        self.menubar.addAction(self.actionLoadDatabase.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Recognition"))
        self.LoadDatabaseButton.setText(_translate("MainWindow", "Load Database"))
        self.actionLoadDatabase.setTitle(_translate("MainWindow", "Load Database.."))
        self.actionLoad_faces.setText(_translate("MainWindow", "Load faces..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
